### ISSUE TITLE
net_dav can put textfile only?

### ISSUE THREAD

**Issue by sanemat** [devrandom/net_dav#3]
I want to put imagefile. 
But I see raised error
  ArgumentError: Content-Length not given and Transfer-Encoding is not `chunked'

**Comment by do11** [comment]
Same exception when uploading gpg-encrypted file into Yandex.Disk webdav using basic auth. This is when installed from `gem install`. It is **resolved**, though, when gem is installed directly from this repo.

Hey, I see you abandoned maintaining this package, but can you, at least, release current version (as 0.6.0 probably) into rubygems so it installs by default by `gem install`?

**Comment by devrandom** [comment]
Did you have any issues building? I had issues last time I tried. If anybody can contribute a patch to bring dependencies and build up to date, that would be appreciated.

On 8 November 2015 10:57:01 GMT-05:00, do11 <notifications@github.com> wrote:
>Same exception when uploading gpg-encrypted file into Yandex.Disk
>webdav using basic auth. This is when installed from `gem install`. It
>is **resolved**, though, when gem is installed directly from this repo.
>
>Hey, I see you abandoned maintaining this package, but can you, at
>least, release current version (as 0.6.0 probably) into rubygems so it
>installs by default by `gem install`?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/devrandom/net_dav/issues/3#issuecomment-154835032

-- 
Sent from my phone. Please excuse my brevity.

**Comment by do11** [comment]
> Did you have any issues building?

No. It was as simple as

    git clone https://github.com/devrandom/net_dav.git
    gem build net_dav.gemspec
    gem install ./net_dav-0.5.0.gem

Centos 6.6, but ruby is old install from the sources: `ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-linux]`

Only problem I had after is that upload for ~2G file is still failed with

```
/usr/local/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill': Timeout::Error (Timeout::Error)
        from /usr/local/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
        from /usr/local/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
        from /usr/local/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1294:in `request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:746:in `start'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1285:in `request'
        from /usr/local/lib/ruby/gems/1.9.1/gems/net_dav-0.5.0/lib/net/dav.rb:171:in `handle_request'
        from /usr/local/lib/ruby/gems/1.9.1/gems/net_dav-0.5.0/lib/net/dav.rb:85:in `request_sending_stream'
        from /usr/local/lib/ruby/gems/1.9.1/gems/net_dav-0.5.0/lib/net/dav.rb:610:in `put'
        from sync-yandex.rb:110:in `block in <main>'
```
until I did `gem install curb`. After that all is smooth.

**Comment by do11** [comment]
Well, I still get timeouts on big files even with *curb* installed. That's unfortunate.

```
/usr/local/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill': Timeout::Error (Timeout::Error)
        from /usr/local/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
        from /usr/local/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
        from /usr/local/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1294:in `request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:746:in `start'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1285:in `request'
        from /usr/local/lib/ruby/gems/1.9.1/gems/net_dav-0.5.0/lib/net/dav.rb:171:in `handle_request'
        from /usr/local/lib/ruby/gems/1.9.1/gems/net_dav-0.5.0/lib/net/dav.rb:85:in `request_sending_stream'
        from /usr/local/lib/ruby/gems/1.9.1/gems/net_dav-0.5.0/lib/net/dav.rb:610:in `put'
        from sync-yandex.rb:125:in `block (2 levels) in <main>'
```
