### ISSUE TITLE
Undefined local variable or method `response'

### ISSUE THREAD

**Issue by mobitar** [devrandom/net_dav#40]
Hello, using the sample code from the wiki:

```
require 'rubygems'
require 'net/dav'

dav = Net::DAV.new(http://192.168.7.28:8085", :curl => false)
dav.verify_server = false
dav.credentials(ENV['DAVUSER'],ENV['DAVPASS'])

dav.find('.',:recursive=>true,:suppress_errors=>true,:filename=>/\.html|\.xml$/) do | item |
  puts "Checking: " + item.url.to_s
  if( item.content =~ /www.wrong.com/ )
    item.content = item.content.gsub("www.wrong.com", "www.right.com")
    puts "Updated: " + item.url.to_s
  end
end
```

I get this exception:

```
lib/net/dav.rb:162:in `handle_request': undefined local variable or method `response' for #<Net::DAV::NetHttpHandler:0x007fc07811b788> (NameError)
Did you mean?  response
	from /Users/mo/.rvm/gems/ruby-2.3.1/gems/net_dav-0.5.1/lib/net/dav.rb:192:in `handle_request'
	from /Users/mo/.rvm/gems/ruby-2.3.1/gems/net_dav-0.5.1/lib/net/dav.rb:150:in `request'
	from /Users/mo/.rvm/gems/ruby-2.3.1/gems/net_dav-0.5.1/lib/net/dav.rb:498:in `propfind'
	from /Users/mo/.rvm/gems/ruby-2.3.1/gems/net_dav-0.5.1/lib/net/dav.rb:531:in `find'
	from script.rb:8:in `<main>'
```

Indeed response is used here without being defined:
https://github.com/devrandom/net_dav/blob/master/lib/net/dav.rb#L162

**Comment by mobitar** [comment]
Update: turns out to be the WebDav client app I was using on Mac. I used this instead and no longer see the above problems: https://github.com/mar10/wsgidav
